### ISSUE TITLE
Custom language domains and URL generation

### ISSUE THREAD

**Issue by chimpanze** [nawork/nawork-uri#11]
Hi!

Following scenario:
3 Websites with 3 Domains and 3 Languages:

www.test.de (DE)
www.test.pl (PL)
www.test.com (EN)

You create a link on the DE website to a link on the PL website.

nawork_uri gets the parameters:

L=2
id=15

Now nawork_uri fetches the Domain from the HTTP_HOST and saves the URL for the DE Domain, which is not correct if you have 1 language per domain.

I hope this is understandable.

Greetings,

Marten

**Comment by thommyhh** [comment]
Hi Marten, I'm sorry that it took so long. Can you tell me which version you are using? Are these just 3 languages on the same tree or do you have different trees?

**Comment by chimpanze** [comment]
Hi!
It is one tree with 3 languages.
You know which environment I'm talking about ;)

**Comment by thommyhh** [comment]
Some time has gone now and I don't know, if you have solved the problem yourself. If not, I have some ideas that might help.

I thought about how the link data is built and handed over to nawork-uri. I looked at the `Nawork\NaworkUri\Controller\Frontend\UrlController`.

In the default case nawork-uri uses the current Hostname to determine the URL. If the target domain is set in the link data, nawork-uri uses that one. The problem with your cross-domain-same-tree-language-links is, that TYPO3 CMS does not set the target domain, because the link points to the same tree and TYPO3 does not know anything about different domains for different languages.

But: nawork-uri has a hook just before the domain determination in `Nawork\NaworkUri\Controller\Frontend\UrlController::params2uri` in lines 61-69. That could be used to set the target domain depending on the given language parameter. You have to split and process the parameters yourself though, as this is before nawork-uri does anything in its processing. But you can of course use the methods from `Nawork\NaworkUri\Utility\GeneralUtility` for exploding the parameters.

The hook existing since version 2.6.0, so it is available in your fork.

Let me know, if this was still helpful. I'm really sorry, that it took so long.

**Comment by thommyhh** [comment]
@chimpanze Any news on this?

**Comment by thommyhh** [comment]
Due to missing feedback I close this now.
